### ISSUE TITLE
Nebular Auth with Custom Headers Backend Integration

### ISSUE THREAD

**Issue by itanimo** [akveo/nebular#1342] opened 2019-04-02 12:11 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [x ] feature request

### Issue description

**Current behavior:**
I followed the auth setup guide and reach a point where I cannot modify the http headers, so I ended up doing my own auth solution. 

So my login function looks like this, how can I modify the current login to add these custom headers to my post requests?

**Expected behavior:**
Ability to add custom header to post requests with nebular auth

**Steps to reproduce:**
1. Setup Nebular Auth
2. Can only do standard http post calls without custom headers

**Related code:**

```
`  login(username: string, password: string) {
        const _url = 'https://192.168.1.2:4444/api/auth/login';
        const headers = new Headers();
        headers.append('X-UDS-User', username);
        headers.append('Content-Type', 'application/json');
        const options = new RequestOptions({ headers: headers });

        return this.http.post(_url, JSON.stringify({ username: username, password: password }), options)
            .map((response: Response) => {
                this.resp_code = response.json();

                if (this.resp_code === 1)
                    sessionStorage.setItem('force_password_change', 'Y');
                sessionStorage.setItem('username', response.headers.get('X-UDS-User'));
                sessionStorage.setItem('token', response.headers.get('X-UDS-Token'));
                sessionStorage.setItem('AccessTime', response.headers.get('X-UDS-AccessTime'));
            });
    }`
```

### Other information:

**npm, node, OS, Browser**
```
Latest release of nebular, chrome, npm, node.
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by nnixaa** [comment] 2019-04-11 09:24
Thanks @itanimo, yes this totally makes sense. Closing as duplicate of https://github.com/akveo/nebular/issues/1232.

**Closed by nnixaa** 2019-04-11 09:24 UTC
