### ISSUE TITLE
Angular 9.0 Upgrade Issue

### ISSUE THREAD

**Issue by elucidsoft** [akveo/nebular#2210] opened 2020-02-09 14:32 UTC
* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

run `ng update @angular/cdk`

Recieve error: `Package "@nebular/theme" has an incompatible peer dependency to "@angular/cdk" (requires "^8.0.0", would install "9.0.0").`

**Expected behavior:**
@angular/cdk updates

**Steps to reproduce:**
run `ng update @angular/cdk`

**Comment by Destreyf** [comment] 2020-02-17 23:25
@elucidsoft 

It'll be nice once the 5.0.0 release comes around, however you may be able to get around this at least for development purposes by issuing an upgrade command with force, this is how i did it in the interim.

```bash
ng update @angular/cdk --force -C
```

`--force` ignores any dependency conflicts YMMV.
`-C` makes it commit any changes it performs to your codebase as an individual commit, this is useful when doing regular angular upgrades so you can step back through to find any issues caused by the automated migrations found within angular's CLI.

I am going to stress that YMMV with this, i haven't had issues building production bundles or running a development serve, but this doesn't mean that you'll have no issues.

**Comment by yggg** [comment] 2020-03-16 09:43
Fixed by #2236

**Closed by yggg** 2020-03-16 09:43 UTC
