### ISSUE TITLE
Context menu is not hidden when user clicks an item. 

### ISSUE THREAD

**Issue by nabeelriaz1001** [akveo/nebular#465] opened 2018-06-04 08:02 UTC
**I'm submitting a ...**  (check one with "x")

* [x ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
I have a logout button in context menu. Context menu is not hidden when I click it. 

**Expected behavior:**
 Context menu should hide.

**Comment by gtame** [comment] 2018-06-08 17:59
Me too.

**Comment by nnixaa** [comment] 2018-06-15 09:34
Duplicate of https://github.com/akveo/nebular/issues/423

**Closed by nnixaa** 2018-06-15 09:34 UTC
