### ISSUE TITLE
Cannot resolve eva-icons in \@nebular\evaicons

### ISSUE THREAD

**Issue by tranvannhatdev** [akveo/nebular#1370] opened 2019-04-09 16:56 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description
Build failed
**Current behavior:**
Build failed with error message:
"ERROR in ./node_modules/@nebular/eva-icons/eva-icons.module.js
Module not found: Error: Can't resolve 'eva-icons' in '~\ClientApp\node_modules\@nebular\eva-icons'"

**Expected behavior:**
Build successful

**Steps to reproduce:**
1. Create new blank angular project with latest version
2. ng add @nebular/theme -> complete without errror
3. cmd: npm install
4. cmd: npm start

**Comment by sarmon** [comment] 2019-04-10 08:25
you can try  ”ng add @nebular/theme@3.4.2“

**Comment by nnixaa** [comment] 2019-04-10 08:31
Here is the cause https://github.com/akveo/nebular/issues/1358#issuecomment-481593025. Closing as duplicate.

**Closed by nnixaa** 2019-04-10 08:31 UTC

**Comment by GregSithole** [comment] 2019-04-10 18:19
I managed to get mine working by first installing eva-icons 
`npm i eva-icons --save`
and then running the following command
`npm i @nebular/eva-icons --save`

Hope it helps

**Comment by sandeepkamathkr** [comment] 2019-06-24 05:11
@GregSithole 
after doing the above step , still i am facing these issue
ERROR in node_modules/@nebular/eva-icons/eva-icons.module.d.ts(1,10): error TS2305: Module '"C:/Dev/Workspaces/efin-ui/node_modules/@nebular/theme"' has no exported member 'NbIconLib
raries'.
node_modules/@nebular/eva-icons/eva-icons.module.d.ts(1,27): error TS2305: Module '"C:/Dev/Workspaces/efin-ui/node_modules/@nebular/theme"' has no exported member 'NbSvgIcon'.

**Comment by yggg** [comment] 2019-08-06 09:22
Thanks for the answer @GregSithole!

@sandeepkamathkr Which `@nebular/theme` version do you use? Could you please post Angular and Nebular dependencies list from `package.json`?
