### ISSUE TITLE
NbDatepicker with min/max can't be optional

### ISSUE THREAD

**Issue by Nolanus** [akveo/nebular#2802] opened 2021-07-29 17:41 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
Adding a NbDatepicker with min and max should requires the input to be set/have a value. An empty value is treated as invalid input.

```
 <nb-datepicker #myDatepicker [min]="myMinDate" [max]="myMaxDate"></nb-datepicker>
            <input [nbDatepicker]="myDatepicker" type="text" nbInput formControlName="date"/>
```

The `error` property of the above `date` control is
```
{ "nbDatepickerMin": { "min": "2021-07-29T17:03:01.331Z", "actual": null }, "nbDatepickerMax": { "max": "2021-08-28T22:00:00.000Z", "actual": null } }
```

**Expected behavior:**
Adding min and max validation should not make the field required implicitly.
Compare the implementation of angular default min and max validators, which considers empty values as valid: https://github.com/angular/angular/blob/6ef06bbb3818f1ede7b3290748d4f04f910f575c/packages/forms/src/validators.ts#L416

**Steps to reproduce:**
Create a datepicker with above mentioned configuration

**Related code:**
https://stackblitz.com/edit/github-xl1wth?file=src%2Fapp%2Fhome%2Fhome.component.html

### Other information:

Problem cause is the `!date` check in the [ngDatepickerMax Validator](https://github.com/akveo/nebular/blob/656ed0fa463aa35c62926de5ec5f17ffeea1494e/src/framework/theme/components/datepicker/datepicker.directive.ts#L407). It seems to try picking up nullish values like null or an empty string to not treat them as invalid input. However, the default NbDateService simply parses the date: `new Date(Date.parse(date)`, where `date` is an empty string. This results in an `Invalid Date` to be returned from the NbDateService and an invalid date is: `!new Date(Date.parse('') === false`

**Angular, Nebular**
angular 11.2.12
nebular 7.0.0

**Comment by chirichok98** [comment] 2021-08-06 08:42
Duplicate of #2745

**Closed by chirichok98** 2021-08-06 08:42 UTC
