### ISSUE TITLE
font awesome icons size

### ISSUE THREAD

**Issue by yedajiang44** [akveo/nebular#1303] opened 2019-03-15 01:58 UTC
`font awesome`icon size too big
![QQ截图20190315095004](https://user-images.githubusercontent.com/25813145/54402657-bd6ea900-4707-11e9-8f3d-d282387281d5.jpg)
html code:
```html
  <nb-actions
    size="medium"
    [class.right]="position === 'normal'"
    [class.left]="position === 'inverse'">
    <nb-action *nbIsGranted="['view', 'user']" >
      <nb-user [nbContextMenu]="userMenu" [name]="user?.name" [picture]="user?.picture"></nb-user>
    </nb-action>
    <nb-action class="control-item"
               icon="fas fa-shopping-cart"
               badgeText="99+"
               badgePosition="top right"
               badgeStatus="danger"></nb-action>
    <nb-action class="control-item" disabled icon="nb-notifications"></nb-action>
    <nb-action class="control-item" icon="nb-email"></nb-action>
    <nb-action class="control-item">
      <nb-search type="rotate-layout" (click)="startSearch()"></nb-search>
    </nb-action>
  </nb-actions>
```
How to keep the size consistent？？？

**Comment by yggg** [comment] 2019-03-18 09:33
Closing as duplicate of https://github.com/akveo/ngx-admin/issues/2064

**Closed** 2019-03-18 09:33 UTC
