### ISSUE TITLE
ngx-admin customized login style 

### ISSUE THREAD

**Issue by mfarhani** [akveo/nebular#628] opened 2018-08-13 10:49 UTC
### Issue type
Style not works
**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by Prefix1802** [comment] 2018-08-13 10:55
@mfarhani

Can you provide more information? What are you doing, what's the error?

**Comment by mfarhani** [comment] 2018-08-13 12:46
@Prefix1802 
I am customizing ngx-admin login, after resolving many errors i managed to change its contents to what i wanted, but the style is not working properly. I edited the _component.scss file as shown below:
`/**
 * @license
 * Copyright Akveo. All Rights Reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */

@import '../../components/layout/layout.component.theme';
@import '../../components/sidebar/sidebar.component.theme';
@import '../../components/card/card.component.theme';
@import '../../components/card/flip-card/flip-card.component.theme';
@import '../../components/card/reveal-card/reveal-card.component.theme';
@import '../../components/tabset/tabset.component.theme';
@import '../../components/route-tabset/route-tabset.component.theme';
@import '../../components/menu/menu.component.theme';
@import '../../components/user/user.component.theme';
@import '../../components/actions/actions.component.theme';
@import '../../components/search/search.component.theme';
@import '../../components/checkbox/checkbox.component.theme';
@import '../../components/progress-bar/progress-bar.component.theme';
@import '../../components/badge/badge.component.theme';
@import '../../components/popover/popover.component.theme';
@import '../../components/context-menu/context-menu.component.theme';
@import '../../components/alert/alert.component.theme';
@import '../../components/input/input.directive.theme'; // Added this line

@mixin nb-theme-components() {

  @include nb-layout-theme();
  @include nb-sidebar-theme();
  @include nb-card-theme();
  @include nd-reveal-card-theme();
  @include nd-flip-card-theme();
  @include nb-tabset-theme();
  @include nb-route-tabset-theme();
  @include nb-menu-theme();
  @include nb-user-theme();
  @include nb-actions-theme();
  @include nb-search-theme();
  @include nb-checkbox-theme();
  @include nb-progress-bar-theme();
  @include nb-badge-theme();
  @include nb-popover-theme();
  @include nb-context-menu-theme();
  @include nb-alert-theme();
  @include nb-input-theme(); // Added this line
}
`
But input fields' height is not correct and the button down below doesn't have the desired styles, even though i'm using the built-in component. 
![image](https://user-images.githubusercontent.com/30834245/44032476-742046a2-9f1c-11e8-933e-2a9d00ba2bf7.png)

**Comment by Prefix1802** [comment] 2018-08-13 14:06
@mfarhani 

For customizing your login page you should follow this guide.

https://akveo.github.io/nebular/docs/auth/configuring-ui#custom-ui-components

If you did that i am assuming that you copied the auth pages from the master repo of nebular. That is where things go wrong because thare are some breaking changes in the auth pages. Instead you should copy the auth pages from RC 10. I myself used the ones from RC 9, but the ones in RC 10 should work. 

You can read about it here:

https://github.com/akveo/ngx-admin/issues/1807.

**Comment by joemak93** [comment] 2018-12-07 07:39
Hello @Prefix1802 @nnixaa , May I know how to remove the "back button" in the page top-left?
<img width="690" alt="screen shot 2018-12-07 at 3 37 43 pm" src="https://user-images.githubusercontent.com/6102695/49633967-4950a500-fa36-11e8-9835-bd7879ad8a1a.png">

**Comment by Prefix1802** [comment] 2018-12-09 08:46
@joemak93 

Dis you follow these steps:

https://github.com/akveo/nebular/blob/master/docs/articles/auth-custom-ui.md

**Comment by joemak93** [comment] 2018-12-10 01:32
@Prefix1802 Yes I did. but I have no idea where to modify that "back arrow", it is out of the "login.component.html"

**Comment by RoshanHalwai** [comment] 2018-12-18 16:41
I am facing the same problem of "back arrow", any help would be appreciated.

**Comment by devrahuldataman** [comment] 2018-12-25 13:03
I am also facing this issue. There is no need of back button in the login screen. admin, please help us.

**Comment by joshua147** [comment] 2019-01-06 03:44
I was able to remove the header and back button by adding the snippet below to my custom auth components scss files. Not sure if this is the best way, but it worked for me.

For example, this went into my auth/login/login.component.scss - Remember to add the StyleURL to the component .ts files if you have no done so already. They are not there out of the box.

` /deep/ .nb-theme-cosmic nb-card-header {
    display: none !important;
  }`

**Comment by dizco** [comment] 2019-01-14 21:02
To remove the back arrow, you should override the `NbAuthComponent` with your own, just like you did for the `NbLoginComponent`.

Then, you change your routing module to look like
```typescript
export const routes: Routes = [
    {
        path: '',
        component: AuthComponent, // <-- Notice this here, use your own instance
        children: [
            {
                path: 'login',
                component: LoginComponent,
            },
        ],
    },
];
```

Obviously, you'll want to create your own instance of `AuthComponent`. Here's mine:
```typescript
import { Component } from '@angular/core';
import { NbAuthComponent } from '@nebular/auth';

@Component({
    selector: 'auth',
    styleUrls: ['./auth.component.scss'],
    template: `
    <nb-layout>
      <nb-layout-column>
        <nb-card>
          <nb-card-body>
            <nb-auth-block>
              <router-outlet></router-outlet>
            </nb-auth-block>
          </nb-card-body>
        </nb-card>
      </nb-layout-column>
    </nb-layout>
  `,
})
export class AuthComponent extends NbAuthComponent {
}
```

You will also need to copy `auth.component.scss` from the nebular repo, unfortunately. But that should be it :)

**Comment by Tibing** [comment] 2019-01-16 16:31
Hi, I think this issue has to be resolved now, I'm closing it. Please, feel free to reopen it or create another one, if you have more questions.

**Closed by Tibing** 2019-01-16 16:31 UTC
Labels: help wanted, module:auth, needs docs, question

**Comment by erikhenriq** [comment] 2019-04-16 03:09
Thanks @dizco <3

**Comment by jasonvuriker** [comment] 2019-09-05 05:47
```
::ng-deep .back-link {
  display: none !important;
}

```

**Comment by martinsnihur** [comment] 2019-09-05 18:21
> ```
> ::ng-deep .back-link {
>   display: none !important;
> }
> ```

Hi, I can't make it work for me, this is what I have in my login.component.scss
@import '../../@theme/styles/themes';

@include nb-install-component() {
    ::ng-deep .back-link {
        display: none !important;
    }
}

Please help!!

**Comment by Iraecio** [comment] 2019-09-17 20:16
@martinsnihur 

// @include nb-install-component() {  <-- remove this line
::ng-deep .back-link {
display: none !important;
}
// } <-- remove this line

**Comment by devpurohit** [comment] 2019-11-04 12:19
What I did was make an app.component.css and put 
`::ng-deep nb-auth nb-card-header {
    display: none !important;
  }`

**Comment by Mustapha-HajRomdhane** [comment] 2020-02-26 13:57
First step is to add styleUrls to your component.ts 👍 

@Component({
  selector: 'nb-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})

Next you can hide header : /deep/ nb-card-header { display: none !important; }
Or Change arrow color : /deep/ a.link.back-link{color: white !important;}

**Comment by siyavash1989** [comment] 2021-05-31 08:00
> To remove the back arrow, you should override the `NbAuthComponent` with your own, just like you did for the `NbLoginComponent`.
> 
> Then, you change your auth routing module to look like
> 
> ```ts
> export const routes: Routes = [
>     {
>         path: '',
>         component: AuthComponent, // <-- Notice this here, use your own instance
>         children: [
>             {
>                 path: 'login',
>                 component: LoginComponent,
>             },
>         ],
>     },
> ];
> ```
> 
> Obviously, you'll want to create your own instance of `AuthComponent`. Here's mine:
> 
> ```ts
> import { Component } from '@angular/core';
> import { NbAuthComponent } from '@nebular/auth';
> 
> @Component({
>     selector: 'auth',
>     styleUrls: ['./auth.component.scss'],
>     template: `
>     <nb-layout>
>       <nb-layout-column>
>         <nb-card>
>           <nb-card-body>
>             <nb-auth-block>
>               <router-outlet></router-outlet>
>             </nb-auth-block>
>           </nb-card-body>
>         </nb-card>
>       </nb-layout-column>
>     </nb-layout>
>   `,
> })
> export class AuthComponent extends NbAuthComponent {
> }
> ```
> 
> You will also need to copy `auth.component.scss` from the nebular repo, unfortunately. But that should be it :)

Hi. I did it but I got an error : If 'nb-card-body' is an Angular component, then verify that it is part of this module.

**Comment by wenhx** [comment] 2022-10-04 03:00
> > To remove the back arrow, you should override the `NbAuthComponent` with your own, just like you did for the `NbLoginComponent`.
> > Then, you change your auth routing module to look like
> > ```ts
> > export const routes: Routes = [
> >     {
> >         path: '',
> >         component: AuthComponent, // <-- Notice this here, use your own instance
> >         children: [
> >             {
> >                 path: 'login',
> >                 component: LoginComponent,
> >             },
> >         ],
> >     },
> > ];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Obviously, you'll want to create your own instance of `AuthComponent`. Here's mine:
> > ```ts
> > import { Component } from '@angular/core';
> > import { NbAuthComponent } from '@nebular/auth';
> > 
> > @Component({
> >     selector: 'auth',
> >     styleUrls: ['./auth.component.scss'],
> >     template: `
> >     <nb-layout>
> >       <nb-layout-column>
> >         <nb-card>
> >           <nb-card-body>
> >             <nb-auth-block>
> >               <router-outlet></router-outlet>
> >             </nb-auth-block>
> >           </nb-card-body>
> >         </nb-card>
> >       </nb-layout-column>
> >     </nb-layout>
> >   `,
> > })
> > export class AuthComponent extends NbAuthComponent {
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You will also need to copy `auth.component.scss` from the nebular repo, unfortunately. But that should be it :)
> 
> Hi. I did it but I got an error : If 'nb-card-body' is an Angular component, then verify that it is part of this module.

I also encountered a similar error:
Error: src/app/auth/auth.component.ts:14:6 - error NG8001: 'nb-layout' is not a known element:
1. If 'nb-layout' is an Angular component, then verify that it is part of this module.
2. If 'nb-layout' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

And all the other nb-* components.
anyone know how to solve this problem?
@dizco @Prefix1802 @Tibing

**Comment by wenhx** [comment] 2022-10-04 09:39
> > > To remove the back arrow, you should override the `NbAuthComponent` with your own, just like you did for the `NbLoginComponent`.
> > > Then, you change your auth routing module to look like
> > > ```ts
> > > export const routes: Routes = [
> > >     {
> > >         path: '',
> > >         component: AuthComponent, // <-- Notice this here, use your own instance
> > >         children: [
> > >             {
> > >                 path: 'login',
> > >                 component: LoginComponent,
> > >             },
> > >         ],
> > >     },
> > > ];
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Obviously, you'll want to create your own instance of `AuthComponent`. Here's mine:
> > > ```ts
> > > import { Component } from '@angular/core';
> > > import { NbAuthComponent } from '@nebular/auth';
> > > 
> > > @Component({
> > >     selector: 'auth',
> > >     styleUrls: ['./auth.component.scss'],
> > >     template: `
> > >     <nb-layout>
> > >       <nb-layout-column>
> > >         <nb-card>
> > >           <nb-card-body>
> > >             <nb-auth-block>
> > >               <router-outlet></router-outlet>
> > >             </nb-auth-block>
> > >           </nb-card-body>
> > >         </nb-card>
> > >       </nb-layout-column>
> > >     </nb-layout>
> > >   `,
> > > })
> > > export class AuthComponent extends NbAuthComponent {
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You will also need to copy `auth.component.scss` from the nebular repo, unfortunately. But that should be it :)
> > 
> > 
> > Hi. I did it but I got an error : If 'nb-card-body' is an Angular component, then verify that it is part of this module.
> 
> I also encountered a similar error: Error: src/app/auth/auth.component.ts:14:6 - error NG8001: 'nb-layout' is not a known element:
> 
> 1. If 'nb-layout' is an Angular component, then verify that it is part of this module.
> 2. If 'nb-layout' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 
> And all the other nb-* components. Anyone know how to solve this problem? @dizco @Prefix1802 @Tibing

After trying for a long time, I discovered the cause of the problem.
After you customize your own AuthComponent, you also need to add it to the declarations list of the NgxAuthModule.
Like this:
`
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    NbAlertModule,
    NbButtonModule,
    NbCardModule,
    NbCheckboxModule,
    NbInputModule,    
    NbLayoutModule,
    NbAuthModule,
    NgxAuthRoutingModule,
  ],
  declarations: [
    NgxAuthComponent,  // <-- here
    NgxLoginComponent,
  ],
})
export class NgxAuthModule {
}
`
And don't forget to import all Modules the template needs.
The error message is unclear, but since I'm new to Angular, I made this silly mistake.

**Comment by zahraa-khalil** [comment] 2022-12-31 12:52
> Hello @Prefix1802 @nnixaa , May I know how to remove the "back button" in the page top-left? <img alt="screen shot 2018-12-07 at 3 37 43 pm" width="690" src="https://user-images.githubusercontent.com/6102695/49633967-4950a500-fa36-11e8-9835-bd7879ad8a1a.png">

add this to your custom login.component.scss, it will hide the back-arrow
::ng-deep {

  .back-link {
    visibility: hidden !important;
  }
}
you could use "display:none" also.
