### ISSUE TITLE
In Firefox v60.0.1 (64-bit) only, all sidebar items and many elements disappear with Light Theme (default theme)

### ISSUE THREAD

**Issue by JavierFuentes** [akveo/nebular#449] opened 2018-05-25 16:58 UTC
### Issue type

**I'm submitting a ...** 

* [X] bug report
* [ ] feature request

### Issue description

**Current behavior:**
In Firefox v60.0.1 (64-bit) for Windows 10 only, all sidebar items and many elements disappear with Light Theme.
It works OK with latest releases of Chrome, Edge and Opera.

**Expected behavior:**
All content should remain visible with Light Theme

**Steps to reproduce:**
Go to __ngx-admin Demo__ with Light Theme activated... menu items and many elements disappear or create a new Angular CLI 6 project with __"@nebular/theme": "2.0.0-rc.8"__ in your package.json

**Browser:**
Firefox v60.0.1 (64-bit) for Windows 10

**Comment by nnixaa** [comment] 2018-05-30 09:59
Hi @JavierFuentes, thanks for reporting. Was it working before rc.8?

**Comment by JavierFuentes** [comment] 2018-06-01 17:38
Sorry @nnixaa, I don't know, but it happens in ngx-admin live Demo too.

**Comment by denStrigo** [comment] 2018-06-04 09:51
Hi @JavierFuentes, could you please add more details(screenshots) how to reproduce this bug. This bug is reproduced on local machine on [Live Demo](http://akveo.com/ngx-admin) too ?

I need more details because I could not reproduce this bug 
![screenshot_1](https://user-images.githubusercontent.com/8480994/40910870-f46cba38-67f5-11e8-90cb-d9a20a9bc091.jpg)

**Comment by JavierFuentes** [comment] 2018-06-09 11:40
Hi again @nnixaa , sorry I can't help you more, but in my computer it show all this page in blank with light theme.

It works ok with latest versions of Chrome, Edge and Opera, but not with Firefox.

![image](https://user-images.githubusercontent.com/5801847/41191004-d62cd7e6-6be8-11e8-9aa1-56abe3d09bec.png)

![image](https://user-images.githubusercontent.com/5801847/41191006-dd44d088-6be8-11e8-8159-c9f368af6f52.png)

It seems to be concern with device width and @media because controls shows if I reduce width... my screen has 1920 x 1080 pixels.

![image](https://user-images.githubusercontent.com/5801847/41191076-324626f8-6bea-11e8-8a0c-abafa627c37f.png)

![image](https://user-images.githubusercontent.com/5801847/41191081-4f4f7ff6-6bea-11e8-9d0e-43ce2bc89c3a.png)

Hope, it can help you.

**Comment by nnixaa** [comment] 2018-06-15 09:37
Well, let's keep it open to see if anyone is experiencing the same.

**Comment by nnixaa** [comment] 2018-11-20 16:51
I guess we are good to close it.

**Closed by nnixaa** 2018-11-20 16:51 UTC
Labels: P2: important, bug, module:theme, needs investigation
