### ISSUE TITLE
Add support of Angular 14

### ISSUE THREAD

**Issue by Jafried15** [akveo/nebular#3078] opened 2022-06-30 11:42 UTC

**Comment by chiragbytes** [comment] 2022-07-14 10:10
@Jafried15 Having same concern, i recently updated my project to angular 14, but nebular theme seems to broken. add support for angular 14

**Comment by HS-Joe** [comment] 2022-07-20 18:19
For instance I didn't had any issue with `npm i --force`

**Comment by RicardoArndt** [comment] 2022-07-21 23:12
The right thing is not to use the install command with --force option.

**Comment by estrudels** [comment] 2022-08-03 14:26
I am also running into this issue using **"@nebular/security": "9.0.3"** and **"@angular/common": "14.0.6"**

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @ingenius-software/ice.admin@0.1.0
npm ERR! Found: @angular/common@14.0.6
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"14.0.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from @nebular/security@9.0.3
npm ERR! node_modules/@nebular/security
npm ERR!   @nebular/security@"9.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by lasertiger** [comment] 2022-08-20 00:14
I too am having problems with it installing in a clean angular14 project.

**Comment by TBG-FR** [comment] 2022-08-20 15:46
> I too am having problems with it installing in a clean angular14 project.

I'll try to work on it and make a PR soon 🤞

**Comment by ramprudvi** [comment] 2022-08-28 16:56
Loosing theme grid design system after upgrade to angular 14 and theme 9.0

**Comment by rashid-naico** [comment] 2022-09-14 04:39
Many dependency issues while installing

**Comment by giacomo** [comment] 2022-09-20 09:59
any news on that?

**Comment by codered13** [comment] 2022-09-21 12:54
I'd like to ask how simple it is for nebular to either ignore already installed packages in the users package.json or to change the packages in its own file to be all angular 14 compatible. The latest release is 9.1.0-rc.4 about 6 days ago and it is using old versions of packages namely one is @angular/animations version 13 as stated here: @angular/animations@"^13.0.0" from @nebular/theme@9.1.0-rc.4

**Comment by MammadK** [comment] 2022-09-21 20:17
please update to angular 14

**Comment by codered13** [comment] 2022-09-29 00:15
I don't understand why no one realises the problem is nebular package needs other packages as part oof its install and they clash with the packages the user has already installed and that nebular uses older versions of them. It's not a simple angular 14 update. Nebular the package uses older other packages and the nebular package itself has to be updated to use the latest of all the packages it needs. I gave a example before of this but no one obviously reads the comments. Look at my previous comment. Once again an example of this is:

@angular/animations version 13 as stated here: @angular/animations@"^13.0.0" from @nebular/theme@9.1.0-rc.4

BTW this issue is the same problem as this one: but once again no one reads:
https://github.com/akveo/nebular/issues/3073

**Comment by basvandorst** [comment] 2022-10-06 12:52
Temporary solution is to add the 14.x versions to the `overrides` section in the `package.json`

```
"overrides": {
    "@angular/animations": "14.2.4",
    "@angular/cdk": "14.2.3",
    ....
}
```

Example: 
```
"dependencies": {
    "@angular/animations": "14.2.4",
    "@angular/cdk": "14.2.3",
    "@angular/common": "14.2.4",
    "@angular/compiler": "14.2.4",
    "@angular/core": "14.2.4",
    "@nebular/theme": "^8.0.0",
    ...
},
"overrides": {
    "@angular/animations": "14.2.4",
    "@angular/cdk": "14.2.3",
    "@angular/common": "14.2.4",
    "@angular/compiler": "14.2.4",
    "@angular/core": "14.2.4"
}
```

Or install with peer-deps should also work: `npm ci --legacy-peer-deps`

**Comment by yalesnikov** [comment] 2022-10-12 03:13
For me it's worked perfectly with `"@angular/cli": "~14.1.3"` but broken after I updated to `"@angular/cdk": "^14.2.1"`.

**Comment by codered13** [comment] 2022-10-14 02:03
Just thought of an idea folks I guess you could backup your packages.json and then force install nebular but yes but after then if it installs older versions of packages it needs then to manually paste over them with what you had originally, I’m just thinking. I’ll give it a go later and comment back.

**Comment by robgor3** [comment] 2022-10-14 06:55
> Temporary solution is to add the 14.x versions to the `overrides` section in the `package.json`
> 
> ```
> "overrides": {
>     "@angular/animations": "14.2.4",
>     "@angular/cdk": "14.2.3",
>     ....
> }
> ```
> 
> Example:
> 
> ```
> "dependencies": {
>     "@angular/animations": "14.2.4",
>     "@angular/cdk": "14.2.3",
>     "@angular/common": "14.2.4",
>     "@angular/compiler": "14.2.4",
>     "@angular/core": "14.2.4",
>     "@nebular/theme": "^8.0.0",
>     ...
> },
> "overrides": {
>     "@angular/animations": "14.2.4",
>     "@angular/cdk": "14.2.3",
>     "@angular/common": "14.2.4",
>     "@angular/compiler": "14.2.4",
>     "@angular/core": "14.2.4"
> }
> ```
> 
> Or install with peer-deps should also work: `npm ci --legacy-peer-deps`

as promising as this workaround was, it's no use when updating with `ng update`., which is especially helpful migrating v13 -> v14 (`Form...` -> `UntypedForm...`)
When using npm@8.3.0 it turns out overrides are respected only after removing `package-lock.json` and `node_modules`, then installing all dependencies once again. On the other hand bumping Angular version using `ng update` requires having these dependencies installed, so overrides are not detected then.

**Comment by giacomo** [comment] 2022-12-20 10:02
should be marked as closed since version 10 of nebular is out and angular 14.2.x is supported.

**Comment by rashid-naico** [comment] 2022-12-20 10:47
good news, but already purchased a new theme

**Closed** 2022-12-20 13:35 UTC
