### ISSUE TITLE
backend auth request is not firing

### ISSUE THREAD

**Issue by rajsanil** [akveo/nebular#100] opened 2017-12-06 11:35 UTC
When i tested api request from postman its working , but the same request is not REACHING TO api server from ngx-admin auth

**Comment by nnixaa** [comment] 2017-12-19 10:51
Hi @rajsanil, please provide a reproducible example so that we can assist.

**Comment by nnixaa** [comment] 2018-01-05 09:25
Closing due to no updates.

**Closed by nnixaa** 2018-01-05 09:25 UTC
Labels: module:auth, needs info
