### ISSUE TITLE
rememberMe=false does not hide checkbox and text from UI

### ISSUE THREAD

**Issue by DmytroLitvinov** [akveo/nebular#650] opened 2018-08-18 13:42 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

At `NbPasswordAuthStrategy.setup` I tried to setup at `forms` for `login` field `rememberMe` to `false` and it should hide from layout( as described at docs near rememberMe field:https://akveo.github.io/nebular/docs/auth/configuring-ui) 

**Expected behavior:**

Hide "Remember me" and checkbox from UI

**Steps to reproduce:**

Open `ngx-admin` template and insert next code:
```
forms: {
      login: {
        rememberMe: false,
      },
    },
```

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
Node v8.9.4
Npm v.6.4.0
OS Ubuntu 16.04
Browser Chrome last version
```

**Angular, Nebular**
```
"@nebular/auth": "2.0.0-rc.10",

"@nebular/auth": {
      "version": "2.0.0-rc.10",
      "resolved": "https://registry.npmjs.org/@nebular/auth/-/auth-2.0.0-rc.10.tgz",
      "integrity": "sha512-5jswHe7CxiLagZu9Mct5oa0FwwelTC2XeHESDUK+tqPO14axikrdM9IFnftMqlQ2NkIMCNeMnIt/91M3dPjGZA=="
    },
```

**Comment by nnixaa** [comment] 2018-08-20 15:18
Hi @DmytroLitvinov, thanks for reporting, but this is a duplicate of #330  which has been fixed and will be available in the next release.

**Closed by nnixaa** 2018-08-20 15:18 UTC

**Comment by DmytroLitvinov** [comment] 2018-08-20 16:14
Sorry for duplication and thanks for the answer.
