### ISSUE TITLE
NbContextMenu - not sure how to trigger methods on click of a menu item

### ISSUE THREAD

**Issue by jjgriff93** [akveo/nebular#866] opened 2018-10-07 21:11 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
At the moment, it's unclear how to easily add actions to a click of a menu item using the `nbContextMenu` component. 

There is some info in the documentation about adding an event listener and using pipe to get which item was clicked, however apart from creating a window alert showing the value that was clicked, I'm not sure how t0 trigger different methods depending on what was clicked.

**Expected behavior:**
I would like to be able to create the menu array with two values instead of just providing a title. I'd like to be able to define a context menu like this: 

```
userMenu = [
    { title: 'Profile', action: 'ProfileClicked()' },
    { title: 'Log out', action: 'logout()' }
]
```

Then passing this into the menu like so `[nbContextMenu]=userMenu`  would trigger the methods I've defined in the array. 

If this isn't possible would really appreciate some help in how I could code this into the below example from the documentation:

```
ngOnInit() {
    this.nbMenuService.onItemClick()
      .pipe(
        filter(({ tag }) => tag === 'my-context-menu'),
        map(({ item: { title } }) => title),
      )
      .subscribe(title => this.window.alert(`${title} was clicked!`));
  }
```

**Steps to reproduce:**
ngx-admin with the example above from the documentation implemented into the header.component.ts

**Comment by nnixaa** [comment] 2018-10-08 09:27
Hi @jjgriff93, currently there is no built-in way, but a menu item accepts an option called `data`, so that you can pass any info into it. So you can pass there som `id` and then check which item is clicked based on that id:

```
userMenu = [
    { title: 'Log out', data: { id: 'logout' } },
]
```

```
ngOnInit() {
    this.nbMenuService.onItemClick()
      .pipe(
        filter(({ tag }) => tag === 'my-context-menu'),
      )
      .subscribe((item: NbMenuItem) => {
		if (item.data.id === 'logout') { ... }
	  });
  }
```

**Comment by jjgriff93** [comment] 2018-10-08 12:54
HI @nnixaa - okay cool, would be great to see a built in way in the future. Thanks very much for the code snippet, that's worked a treat :)

**Comment by nnixaa** [comment] 2018-10-09 08:05
Great! Closing it then as a duplicate of #624 (request to add an `id` property to handle the item properly).

**Closed by nnixaa** 2018-10-09 08:05 UTC
Labels: enhancement, faq, module:components, question

**Comment by el7or** [comment] 2019-10-17 11:46
```
constructor( private sidebarService: NbSidebarService,
               private menuService: NbMenuService,
               private userService: UserService) {
  }

  ngOnInit() {
    this.userService.getUsers()
      .subscribe(( users: any ) => this.user = users.nick);
    this.menuService.onItemClick().subscribe(( event ) => {
      this.onItemSelection(event.item.title);
    })
  }
```

**Comment by ArslanAhmet** [comment] 2019-10-23 07:18
this.menuService.onItemClick().subscribe((event) => {
      if (event.item.title === 'Log out') {
        console.log('logout clicked');
      }
    });

**Comment by jackson1992121** [comment] 2020-04-17 02:13
Thanks, @ArslanAhmet. Your answer is succinct and clear. It was helpful.

**Comment by aabi0044** [comment] 2020-05-20 20:45
@ArslanAhmet is there a way to get the value of main menu item, not the submenu item?

**Comment by sranmanpreet** [comment] 2022-01-19 02:48
> @ArslanAhmet is there a way to get the value of main menu item, not the submenu item?

You can pass string data from main menu item into nbContextMenuTag.

```
<div *ngFor='let record of records'>
    <div [nbContextMenu]='contextMenuItems' nbContextMenuTag='{{record.id}}' nbContextMenuTrigger="click">
    </div>
</div>
```

```
const records = [{id: 1, name: "Record A"}, {id:2, name: "Record B"}];

ngOnInit(): void {
  this.nbMenuService.onItemClick()
    .subscribe(
      (menuBag:NbMenuBag) => {
        console.log("Record Id: " + menuBag.tag);
      }
    );
}
```

**Comment by theFallen78** [comment] 2022-03-22 21:11
i was trying to intergrate with angular fire and this worked for me 
`  userMenu = [ 
    { title: 'Log out', data: { id: 'logout' }  } 
  ];

  constructor(private sidebarService: NbSidebarService,
              private menuService: NbMenuService,
              private themeService: NbThemeService,
              private userService: UserData,
              private layoutService: LayoutService,
              public authService:AuthService,
              private breakpointService: NbMediaBreakpointsService) {
  }

  ngOnInit() {
    this.menuService.onItemClick().subscribe((e)=>{
    if(e.item.data.id == "logout"){
      this.authService.logout()
    }
    })
}
`
