### ISSUE TITLE
nb-select selection issue

### ISSUE THREAD

**Issue by KostyaDanovsky** [akveo/nebular#1230] opened 2019-02-13 12:25 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

If `nb-select` was rendered and only after that list of options come from the server, it's not possible to select any option

**Expected behavior:**

If we load list of option after `nb-select` rendering it should be possible to select value

**Steps to reproduce:**

1) create component with `nb-select` and list of `nb-option`, which is generated by `ngFor` operator. 
2) update list of possible options using `setTimeout` f.e. in your component
3) try to select new option

**Comment by swbradshaw** [comment] 2019-02-25 19:11
I think this is a dupe of #1063

**Comment by aefox** [comment] 2019-03-06 12:56
this actually works as expected as long as your `nb-option`s correctly set their `value` attribute. please see this [stackblitz](https://stackblitz.com/edit/github-kkt2hz-ugcvqu?file=src%2Fapp%2Fhome%2Fhome.component.html) for examples. If you remove the `[value]="item"` on the `nb-option`s you'll see the problem you mentioned reproduces. but this is an incorrect usage of `nb-option`. cc: @nnixaa maybe this needs better documentation?

*note:* there's currently an issue with using `ng-container` as wrapper for `nb-option` but a fix is coming up really fast

**Comment by yggg** [comment] 2019-04-11 18:22
Fixed in #1299

**Closed by yggg** 2019-04-11 18:22 UTC
Labels: Backlog, P2: important, bug, module:theme

**Comment by glaucomorais** [comment] 2019-07-28 09:27
Ng-container still can't be used inside a nb-select.
The [stackblitz ](https://stackblitz.com/edit/github-kkt2hz-ugcvqu?file=src%2Fapp%2Fhome%2Fhome.component.html) mentioned by @aefox has the problem as well.

**Comment by BruneXX** [comment] 2019-08-22 20:44
Hi @glaucomorais, Really? I'm experiencing the same issue? currently there's no workaround for this? thanks!

**Comment by caiusCitiriga** [comment] 2020-12-02 10:03
Still having this issue... and the example provided in the stackblitz does not work too. Any ideas?
My code looks like this

```html
<nb-select id="mainCategory" fullWidth formControlName="mainCategory"
            (selectedChange)="onMainCategoryChange($event, null)">
    <nb-option *ngFor="let category of existingMainCategories" [value]="category">
        {{category | extractCatLocalizedName}}
    </nb-option>
</nb-select>
```

And the category structure is this one: 
```ts
export interface ICategoryPOJO {
    value: string;
    displayName: {[k: string]: string};
}
```

Also the documentation states that the `NbSelectComponent` has a method called `setValue` but this method is **protected** and not accessible from the hosts using it.  

Not with a clean way of course... but still, it does not set the value anyway...
