### ISSUE TITLE
Add Switcher component directly to Nebular framework

### ISSUE THREAD

**Issue by alexsintoni** [akveo/nebular#1196] opened 2019-01-31 06:45 UTC
* [ ] bug report
* [x] feature request

### Issue description

In my opinion, it would be nice to have the [Switcher Component](https://github.com/akveo/ngx-admin/tree/master/src/app/%40theme/components/switcher) which is in [ngx-admin](https://github.com/akveo/ngx-admin) dashboard directly in [Nebular](https://akveo.github.io/nebular/) framework.

**Comment by nnixaa** [comment] 2019-06-04 15:30
Closing as a duplicate of https://github.com/akveo/nebular/issues/778

**Closed by nnixaa** 2019-06-04 15:30 UTC
Labels: P3: minor, enhancement, module:components
