### ISSUE TITLE
Wrong implementation of "getTokenExpDate" in NbAuthOAuth2Token

### ISSUE THREAD

**Issue by schuettecarsten** [akveo/nebular#564] opened 2018-07-15 14:10 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [X] bug report
* [ ] feature request

### Issue description

**Related code:**
```
  /**
   * Returns expiration date
   * @returns Date
   */
  getTokenExpDate(): Date {
    if (!this.token.hasOwnProperty('expires_in')) {
      return null;
    }

    const date = new Date();
    date.setUTCSeconds(new Date().getUTCSeconds() + Number(this.token.expires_in));

    return date;
  }
```

Assuming token object will contain the number of seconds when the token expires in 'expires_in'. The number of seconds is valid at the moment when the token is received from the server. The client can use this information to calculate the exact expiration time of the token when the token is received.

The current getter implementation will add the number of seconds to the current date/time everytime the getter is called, which might be hours or days later and which will return an expiration date that's always in the future. This is wrong.

### Other information:

**Angular, Nebular**
```
Nebular 2.0.0-rc.9
```

**Comment by alain-charles** [comment] 2018-07-16 07:08
I agree the implementation above is wrong.
I sent a pull request three days ago concerning refreshToken management and i have proposed a correction for that because i needed it to be correct.
In the constuctor of the NbAuthOauth2Token, the proposed code search the 'exp' property in the token's payload if any, and if not found, uses the expires_in to calculate and store the expiration date.
```
    if (!this.expDate) {
      if (this.token && Object.keys(this.token).length > 0) {
        const decoded = this.getPayload();
        if (decoded.hasOwnProperty('exp')) {
          this.expDate = new Date(decoded.exp);
        }
      }
      if (!this.expDate) {
        if (this.token.expires_in) {
        this.expDate = new Date();
        this.expDate.setTime(this.expDate.getTime() + Number(this.token.expires_in) * 1000);
        }
      }
    }
```
If the code is merged by @nnixaa , i think this issue will be corrected.

**Comment by schuettecarsten** [comment] 2018-07-16 08:58
@alain-charles you mean your PR https://github.com/akveo/nebular/pull/560? It's currently blocked for merge :-(

**Comment by alain-charles** [comment] 2018-07-16 09:11
@schuettecarsten yes exactly.
The code has to be reviewed by nnixaa before he merges, especially because there are quite heavy changes in this PR and architectural questions.
So it may take a little time, but we are on our way.

**Comment by chhatrapati** [comment] 2018-07-16 09:18
Hi guys can you please help me in #566

**Comment by schuettecarsten** [comment] 2018-07-16 09:18
@alain-charles Maybe it's a good idea to move the Bugfix into a separate PR?

**Comment by nnixaa** [comment] 2018-07-16 10:59
Agree with @schuettecarsten, it makes more sense to fix this bug separately.
@alain-charles not sure about the proposed solution, as this part:
```
if (this.token.expires_in) {
  this.expDate = new Date();
  this.expDate.setTime(this.expDate.getTime() + Number(this.token.expires_in) * 1000);
}
```
still has the same issue - token will never be expired as we always add `expires_in` to the current datetime.

Also, the `exp` property is not a part of the specification https://tools.ietf.org/html/rfc6749#section-4.3.3 so I believe it should not be added into the default OAuth2 token implementation.

The way I see it - we should store the date-time when the token is originally received from the backend and then calculate the expiration based on the total of `token_received_date` + `expires_in`. What do you think?

**Comment by alain-charles** [comment] 2018-07-16 12:12
@nnixaa have a look at the entire code block i posted above (maybe the code is not clear as it is but i think it's working)

If the expiration date is set (i.e. getting from storage), we do nothing so i think the issue is corrected.
If not (coming back from backend), we set the expiration date:
-  if the exp property is found (case of jwt token)  to the exp value,
- and if not, we calculate and store the expdate from the expires_in field (part of the RFC 6749).

I agree we could exclude the exp part from the basic Oauth2 token and only implement the expires_in part. So in this case maybe we could create an NbOauth2JwtToken using the playload's exp field instead of the exprires-in field of the token itself ?

**Closed** 2018-07-26 13:58 UTC
Labels: P1: urgent, bug, module:auth
