### ISSUE TITLE
Fix lazy loading in Tab component

### ISSUE THREAD

**Issue by ESadouski** [akveo/nebular#1827] opened 2019-07-17 11:43 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Lazy loading doesn't work. Content loaded even if it's not active

**Expected behavior:**
When tab marked as lazy-loaded it should be initialized only when its active 

**Steps to reproduce:**
Mark tab as lazy=true

**Related code:**

```
  @Input()
  set lazyLoad(val: boolean) {
    this.init = convertToBoolProperty(val);
  }
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
<!--
Check your `package-lock.json` or locate a `package.json` in the `node_modules` folder.
-->
```

**Comment by ESadouski** [comment] 2019-07-17 11:46
For those who faced this problem, `route-tabset` can be used as a temporary solution. Or please read https://github.com/angular/angular/issues/13921#issuecomment-272660678

**Comment by maihannijat** [comment] 2019-07-17 12:21
Duplicate of #1820

**Comment by redriverit** [comment] 2020-05-12 15:38
Any Update on this? I am seeing all content within my tabs load instantly and not when the tab is active. As mentioned above [lazyLoad] does not change the functionality:
<nb-tab tabTitle="Parties" [lazyLoad]="false">

**Comment by dmk1111** [comment] 2020-12-09 15:55
Hi, guys! Any update on this? For now, with `[lazyLoad]="false"` content is not rendered in the template but all hooks (calls to backend, etc) in child components are still executed. Is there a way to restrict this completely until tab is selected first time? This is pretty annoying in case we have a lot of tabs.

**Closed** 2021-11-15 10:16 UTC
Labels: bug, P2: important, quality
