### ISSUE TITLE
NbAutocompleteDirective : input to disable focus on input on value change

### ISSUE THREAD

**Issue by jornetsimon** [akveo/nebular#2355] opened 2020-05-10 14:45 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**
When a value is set to the input bound to an Autocomplete, and handled by _writeValue()_, the input is focused.

**Expected behavior:**
A new NbAutocompleteDirective boolean input to manage this behaviour.

**Steps to reproduce:**

**Related code:**
autocomplete.directive.ts 
``` typescript
@Input() focusOnInputOnValueChange: boolean;
...
handleInputValueUpdate() {
 if (this.focusOnInputOnValueChange) {
  this.hostRef.nativeElement.focus();
 }
}
```

**Comment by katebatura** [comment] 2021-09-08 10:12
Closing as duplicate of #2401

**Closed by katebatura** 2021-09-08 10:12 UTC
