### ISSUE TITLE
NbTimePicker clears data-bound value when losing focus

### ISSUE THREAD

**Issue by DDoerner** [akveo/nebular#2674] opened 2021-02-17 10:39 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Under the condition that 
1. the value of a nb-timepicker is bound via ngModel or formControl and
2. the user opens the timepicker overlay and dismisses it by clicking outside

then the visual input will reset to the placeholder value, while the data bound to it is not updated.

Example:
- I define a nb-timepicker like `<input [(ngModel)]="date" [nbTimePicker]="picker" />`
- I set `this.date = new Date()` in the code-behind file
- The timepicker displays the current time in the picker input
- I open the timepicker overlay by clicking on it
- I dismiss the overlay without confirming it by clicking outside
- The input resets to the placeholder text 'HH:mm'
- The value "date" remains unchanged

Note:
The issue does not occur if the timepicker overlay has been manually confirmed with any value at least once.

**Expected behavior:**
A dismissed timepicker overlay should not change the displayed input value.

**Steps to reproduce:**
The issue already occurs with the ngModel / formControl example in the documentation: 
- The example: https://akveo.github.io/nebular/example/timepicker/timepicker-form-control.component
- The documentation page: https://akveo.github.io/nebular/docs/components/timepicker/overview

**Related code:**
See code used in the docs above.

**Comment by unumtresocto** [comment] 2021-04-20 11:46
Closing as duplicate of #2629

**Closed by unumtresocto** 2021-04-20 11:46 UTC

**Comment by billy19960629** [comment] 2023-08-01 02:52
Not the same problem, the original value is displayed after canceling, but the bound data has changed
