### ISSUE TITLE
Cannot modify auth login page or other auth component's html.

### ISSUE THREAD

**Issue by Safo91** [akveo/nebular#404] opened 2018-05-03 10:32 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Cannot modify login page or auth modules even after manual input.

**Expected behavior:**
When I edit the login page html, I should see the changes im doing?

**Steps to reproduce:**
import the auth sources, change the html, changes don't apply on the login page.

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
```
{
  "name": "ngx-admin",
  "version": "2.1.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/akveo/ngx-admin.git"
  },
  "bugs": {
    "url": "https://github.com/akveo/ngx-admin/issues"
  },
  "scripts": {
    "ng": "ng",
    "conventional-changelog": "conventional-changelog",
    "start": "ng serve",
    "build": "ng build",
    "build:prod": "npm run build -- --prod --aot",
    "test": "ng test -sr",
    "test:coverage": "rimraf coverage && npm run test -- -cc",
    "lint": "ng lint --type-check",
    "lint:fix": "ng lint --fix",
    "lint:styles": "stylelint ./src/**/*.scss",
    "lint:ci": "npm run lint && npm run lint:styles",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "ng e2e",
    "docs": "compodoc -p src/tsconfig.app.json -d docs",
    "docs:serve": "compodoc -p src/tsconfig.app.json -d docs -s",
    "prepush": "npm run lint:ci",
    "release:changelog": "npm run conventional-changelog -- -p angular -i CHANGELOG.md -s"
  },
  "dependencies": {
    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "~5.2.6",
    "@angular/common": "~5.2.6",
    "@angular/compiler": "~5.2.6",
    "@angular/core": "~5.2.6",
    "@angular/forms": "~5.2.6",
    "@angular/http": "~5.2.6",
    "@angular/platform-browser": "~5.2.6",
    "@angular/platform-browser-dynamic": "~5.2.6",
    "@angular/router": "~5.2.6",
    "@asymmetrik/ngx-leaflet": "3.0.1",
    "@nebular/auth": "2.0.0-rc.6",
    "@nebular/theme": "2.0.0-rc.6",
    "@nebular/security": "2.0.0-rc.6",
    "@ng-bootstrap/ng-bootstrap": "1.0.0",
    "@swimlane/ngx-charts": "7.0.1",
    "angular2-chartjs": "0.4.1",
    "angular2-toaster": "4.0.1",
    "bootstrap": "4.0.0",
    "chart.js": "2.7.1",
    "ckeditor": "4.7.3",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.1",
    "echarts": "^4.0.2",
    "font-awesome": "4.7.0",
    "intl": "1.2.5",
    "ionicons": "2.0.1",
    "leaflet": "1.2.0",
    "nebular-icons": "1.0.6",
    "ng2-ckeditor": "1.1.13",
    "ng2-smart-table": "1.2.2",
    "ng2-tree": "2.0.0-rc.4",
    "ngx-echarts": "2.0.1",
    "normalize.css": "6.0.0",
    "pace-js": "1.0.2",
    "roboto-fontface": "0.8.0",
    "rxjs": "5.5.5",
    "socicon": "3.0.5",
    "tinymce": "4.5.7",
    "typeface-exo": "0.0.22",
    "web-animations-js": "2.2.5",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "1.7.1",
    "@angular/compiler-cli": "~5.2.6",
    "@angular/language-service": "~5.2.6",
    "@compodoc/compodoc": "1.0.1",
    "@types/googlemaps": "3.30.4",
    "@types/d3-color": "1.0.5",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/leaflet": "1.2.3",
    "@types/node": "6.0.90",
    "codelyzer": "4.0.2",
    "conventional-changelog-cli": "1.3.4",
    "husky": "0.13.3",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "npm-run-all": "4.0.2",
    "protractor": "5.1.2",
    "rimraf": "2.6.1",
    "stylelint": "7.13.0",
    "ts-node": "3.2.2",
    "tslint": "5.7.0",
    "tslint-language-service": "0.9.6",
    "typescript": "2.5.3"
  }
}

```

**Comment by nnixaa** [comment] 2018-05-10 15:00
Hey @Safo91, please follow the documentation as it should work out of the box. Could you please provide a reproducible example also?

**Comment by Safo91** [comment] 2018-05-10 15:06
I opened this issue over in ngx forum, ill copy the issue here:

I want to edit the auth sources in nebular, to do this, you mentioned I should copy the sources from the framework/auth/components folder over to my project. I proceeded with that, but I simply copied the login.component.ts (NbLoginComponent) and I got the following error.



> Uncaught Error: Template parse errors:
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("r *ngFor="let socialLink of socialLinks">
              <a *ngIf="socialLink.link"
                 [ERROR ->][routerLink]="socialLink.link"
                 [attr.target]="socialLink.target"
                 [a"): ng:///ThemeModule/NgxLoginComponent.html@74:17
'nb-auth-block' is not a known element:
1. If 'nb-auth-block' is an Angular component, then verify that it is part of this module.
2. If 'nb-auth-block' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

this is within login.component.ts template html <nb-auth-block> not being part of the module.

here is my theme.module.ts

```
`
import { ModuleWithProviders, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

import {
  NbActionsModule,
  NbCardModule,
  NbLayoutModule,
  NbMenuModule,
  NbRouteTabsetModule,
  NbSearchModule,
  NbSidebarModule,
  NbTabsetModule,
  NbThemeModule,
  NbUserModule,
  NbCheckboxModule,
  NbPopoverModule,
  NbContextMenuModule,
} from '@nebular/theme';

import {
  NbAuthComponent,
  // Notice you have to remove NbLoginComponent from here
  NbLogoutComponent,
  NbRegisterComponent,
  NbRequestPasswordComponent,
  NbResetPasswordComponent,
} from '@nebular/auth';

import { NgxLoginComponent } from './components/auth/components/login/login.component';


import { NbSecurityModule } from '@nebular/security';

import {
  FooterComponent,
  HeaderComponent,
  SearchInputComponent,
  ThemeSettingsComponent,
  ThemeSwitcherComponent,
  TinyMCEComponent,
} from './components';
import { CapitalizePipe, PluralPipe, RoundPipe, TimingPipe } from './pipes';
import {
  OneColumnLayoutComponent,
  SampleLayoutComponent,
  ThreeColumnsLayoutComponent,
  TwoColumnsLayoutComponent,
} from './layouts';
import { DEFAULT_THEME } from './styles/theme.default';
import { COSMIC_THEME } from './styles/theme.cosmic';

const BASE_MODULES = [CommonModule, FormsModule, ReactiveFormsModule];

const NB_MODULES = [
  NbCardModule,
  NbLayoutModule,
  NbTabsetModule,
  NbRouteTabsetModule,
  NbMenuModule,
  NbUserModule,
  NbActionsModule,
  NbSearchModule,
  NbSidebarModule,
  NbCheckboxModule,
  NbPopoverModule,
  NbContextMenuModule,
  NgbModule,
  NbSecurityModule, // *nbIsGranted directive
];

const COMPONENTS = [
  ThemeSwitcherComponent,
  HeaderComponent,
  FooterComponent,
  SearchInputComponent,
  ThemeSettingsComponent,
  TinyMCEComponent,
  OneColumnLayoutComponent,
  SampleLayoutComponent,
  ThreeColumnsLayoutComponent,
  TwoColumnsLayoutComponent,
];

const PIPES = [
  CapitalizePipe,
  PluralPipe,
  RoundPipe,
  TimingPipe,
];

const NB_THEME_PROVIDERS = [
  ...NbThemeModule.forRoot(
    {
      name: 'cosmic',
    },
    [ DEFAULT_THEME, COSMIC_THEME ],
  ).providers,
  ...NbSidebarModule.forRoot().providers,
  ...NbMenuModule.forRoot().providers,
];

@NgModule({
  imports: [...BASE_MODULES, ...NB_MODULES],
  exports: [...BASE_MODULES, ...NB_MODULES, ...COMPONENTS, ...PIPES],
  declarations: [...COMPONENTS, NgxLoginComponent, ...PIPES],
})
export class ThemeModule {
  static forRoot(): ModuleWithProviders {
    return <ModuleWithProviders>{
      ngModule: ThemeModule,
      providers: [...NB_THEME_PROVIDERS],
    };
  }
}
`
```
app.routing.module.ts

```
`import { NgxLoginComponent } from './@theme/components/auth/components/login/login.component';
import { ExtraOptions, RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';
import {
  NbAuthComponent,
  // NbLoginComponent,
  NbLogoutComponent,
  NbRegisterComponent,
  NbRequestPasswordComponent,
  NbResetPasswordComponent,
} from '@nebular/auth';

const routes: Routes = [
  { path: 'pages', loadChildren: 'app/pages/pages.module#PagesModule' },
  {
    path: 'auth',
    component: NbAuthComponent,
    children: [
      {
        path: '',
        component: NgxLoginComponent,
      },
      {
        path: 'login',
        component: NgxLoginComponent,
      },
      {
        path: 'register',
        component: NbRegisterComponent,
      },
      {
        path: 'logout',
        component: NbLogoutComponent,
      },
      {
        path: 'request-password',
        component: NbRequestPasswordComponent,
      },
      {
        path: 'reset-password',
        component: NbResetPasswordComponent,
      },
    ],
  },
  { path: '', redirectTo: 'pages', pathMatch: 'full' },
  { path: '**', redirectTo: 'pages' },
];

const config: ExtraOptions = {
  useHash: true,
};

@NgModule({
  imports: [RouterModule.forRoot(routes, config)],
  exports: [RouterModule],
})
export class AppRoutingModule {
}
`

```

and my login.component.ts that I copied over and changed the name to NgxLoginComponent.

```
`/**
 * @license
 * Copyright Akveo. All Rights Reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 */
import { getDeepFromObject } from '@nebular/auth/helpers';
import { NB_AUTH_OPTIONS, NbAuthResult, NbAuthService, NbAuthSocialLink } from '@nebular/auth';
import { Component, Inject } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'nb-login',
  template: `
    <nb-auth-block>
      <h2 class="title">Sign INSERT CHANGES HERE</h2>
      <small class="form-text sub-title">Hello! Sign in with your username or email</small>

      <form (ngSubmit)="login()" #form="ngForm" autocomplete="nope">

        <div *ngIf="showMessages.error && errors && errors.length > 0 && !submitted"
             class="alert alert-danger" role="alert">
          <div><strong>Oh snap!</strong></div>
          <div *ngFor="let error of errors">{{ error }}</div>
        </div>

        <div *ngIf="showMessages.success && messages && messages.length > 0 && !submitted"
             class="alert alert-success" role="alert">
          <div><strong>Hooray!</strong></div>
          <div *ngFor="let message of messages">{{ message }}</div>
        </div>

        <div class="form-group">
          <label for="input-email" class="sr-only">Email address</label>
          <input name="email" [(ngModel)]="user.email" id="input-email" pattern=".+@.+\..+"
                 class="form-control" placeholder="Email address" #email="ngModel"
                 [class.form-control-danger]="email.invalid && email.touched" autofocus
                 [required]="getConfigValue('forms.validation.email.required')">
          <small class="form-text error" *ngIf="email.invalid && email.touched && email.errors?.required">
            Email is required!
          </small>
          <small class="form-text error"
                 *ngIf="email.invalid && email.touched && email.errors?.pattern">
            Email should be the real one!
          </small>
        </div>

        <div class="form-group">
          <label for="input-password" class="sr-only">Password</label>
          <input name="password" [(ngModel)]="user.password" type="password" id="input-password"
                 class="form-control" placeholder="Password" #password="ngModel"
                 [class.form-control-danger]="password.invalid && password.touched"
                 [required]="getConfigValue('forms.validation.password.required')"
                 [minlength]="getConfigValue('forms.validation.password.minLength')"
                 [maxlength]="getConfigValue('forms.validation.password.maxLength')">
          <small class="form-text error" *ngIf="password.invalid && password.touched && password.errors?.required">
            Password is required!
          </small>
          <small
            class="form-text error"
            *ngIf="password.invalid && password.touched && (password.errors?.minlength || password.errors?.maxlength)">
            Password should contains
            from {{ getConfigValue('forms.validation.password.minLength') }}
            to {{ getConfigValue('forms.validation.password.maxLength') }}
            characters
          </small>
        </div>

        <div class="form-group accept-group col-sm-12">
          <nb-checkbox name="rememberMe" [(ngModel)]="user.rememberMe">Remember me</nb-checkbox>
          <a class="forgot-password" routerLink="../request-password">Forgot Password?</a>
        </div>

        <button [disabled]="submitted || !form.valid" class="btn btn-block btn-hero-success"
                [class.btn-pulse]="submitted">
          Sign In
        </button>
      </form>

      <div class="links">

        <ng-container *ngIf="socialLinks && socialLinks.length > 0">
          <small class="form-text">Or connect with:</small>

          <div class="socials">
            <ng-container *ngFor="let socialLink of socialLinks">
              <a *ngIf="socialLink.link"
                 [routerLink]="socialLink.link"
                 [attr.target]="socialLink.target"
                 [attr.class]="socialLink.icon"
                 [class.with-icon]="socialLink.icon">{{ socialLink.title }}</a>
              <a *ngIf="socialLink.url"
                 [attr.href]="socialLink.url"
                 [attr.target]="socialLink.target"
                 [attr.class]="socialLink.icon"
                 [class.with-icon]="socialLink.icon">{{ socialLink.title }}</a>
            </ng-container>
          </div>
        </ng-container>

        <small class="form-text">
          Don't have an account? <a routerLink="../register"><strong>Sign Up</strong></a>
        </small>
      </div>
    </nb-auth-block>
  `,
})
export class NgxLoginComponent {

  redirectDelay: number = 0;
  showMessages: any = {};
  provider: string = '';

  errors: string[] = [];
  messages: string[] = [];
  user: any = {};
  submitted: boolean = false;
  socialLinks: NbAuthSocialLink[] = [];

  constructor(protected service: NbAuthService,
              @Inject(NB_AUTH_OPTIONS) protected config = {},
              protected router: Router) {

    this.redirectDelay = this.getConfigValue('forms.login.redirectDelay');
    this.showMessages = this.getConfigValue('forms.login.showMessages');
    this.provider = this.getConfigValue('forms.login.provider');
    this.socialLinks = this.getConfigValue('forms.login.socialLinks');
  }

  login(): void {
    this.errors = this.messages = [];
    this.submitted = true;

    this.service.authenticate(this.provider, this.user).subscribe((result: NbAuthResult) => {
      this.submitted = false;

      if (result.isSuccess()) {
        this.messages = result.getMessages();
      } else {
        this.errors = result.getErrors();
      }

      const redirect = result.getRedirect();
      if (redirect) {
        setTimeout(() => {
          return this.router.navigateByUrl(redirect);
        }, this.redirectDelay);
      }
    });
  }

  getConfigValue(key: string): any {
    return getDeepFromObject(this.config, key, null);
  }
}
`
```

any other files that require changes to just change the login.html/login component? copying the sources over and editing them is not applying any changes whatsoever.

thank you for the answers!

**Comment by nnixaa** [comment] 2018-05-11 09:30
@Safo91 have you imported RouterModule into your module?

**Comment by Safo91** [comment] 2018-05-11 12:07
would that go into theme.module.ts or app.module.ts?

**Comment by Safo91** [comment] 2018-05-14 10:52
aplogies for asking for handholding as nothing I've attempted has worked so far. I followed the auth guide to a T and still manage to get issue with NbAuthComponent.

Steps I've taken:

1. Clean install of Nebular latest version
2. Copy over auth sources from frameworks/auth/components into my project
3. Change the import from @nebular/auth to my copied over sources
4. Save project
5. Get error listed above (NbAuthComponent is not imported in a module) even though its listed under app.module.ts or theme.module.ts

app.routing-module.ts is also modified to use the copied over sources rather than @nebular/auth


I can provide more details if needed, thanks again!

**Comment by nnixaa** [comment] 2018-05-14 10:54
@Safo91 please upload your project to https://stackblitz.com/

**Comment by Safo91** [comment] 2018-05-14 11:27
https://stackblitz.com/edit/angular-4fxnu3?embed=1&file=src/main.ts

**Comment by Safo91** [comment] 2018-05-20 17:04
@nnixaa I guess you guys have your hands full on upgrading to angular 6, did the project I attach reach you? I'm still facing the same issue

**Comment by nnixaa** [comment] 2018-05-24 11:36
Hi @Safo91, I have just checked your archive, and from the first look - you copied the whole auth module, not only the components. Then you never registered copied components in any module (as per step 2 from the docs https://akveo.github.io/nebular/#/docs/auth/configuring-ui).
I'd suggest you start over and carefully go through each spets double checking you didn't miss anything.

**Comment by ahall-medullan** [comment] 2018-05-25 23:11
has anyone gotten this to work? I am getting the same kinds of errors. my custom form is showing but I get `ERROR TypeError: Nb auth provider 'null' is not registered` when I submit the register form. someone should push a project that has a working example of one of the auth forms being customized.

**Comment by ahall-medullan** [comment] 2018-05-25 23:43
I found the issue for my problem. It was a breaking change provider was changed to strategy, after I started using the **starter-kit** branch. y'all need to keep the starter-ket branch up to date or advise that it is out of sync with master

**Comment by Safo91** [comment] 2018-05-27 18:17
so my issue is because the starter pack is outdated? @ahall-medullan

**Comment by ahall-medullan** [comment] 2018-05-28 14:12
In my case, that was the primary issues. I had other side issues, I looked back at the instructions and followed them to a T, and that got rid of the other issue. ensure you only copy the components folders, not the services etc. I also had to change the imports in the components as follows:
```
import { NbAuthSocialLink, NbAuthService, NB_AUTH_OPTIONS, NbAuthResult } from '@nebular/auth';
import { getDeepFromObject } from '@nebular/auth/helpers'; 
```

**Comment by ahall-medullan** [comment] 2018-05-28 17:42
ensure your app-routing.module.ts is importing your components from the path that you copied them to and not from nebular, and those components are being used on the routes config. mine looks like this
```
import {
  DxAuthComponent,
  DxLoginComponent,
  DxLogoutComponent,
  DxRegisterComponent,
  DxRequestPasswordComponent,
  DxResetPasswordComponent,
} from './@theme/components/auth';
```

and 
```
const routes: Routes = [
  { path: 'pages', loadChildren: 'app/pages/pages.module#PagesModule' },
  {
    path: 'auth',
    component: DxAuthComponent,
    children: [
      {
        path: '',
        component: DxLoginComponent,
      },
      {
        path: 'login',
        component: DxLoginComponent,
      },
      {
        path: 'register',
        component: DxRegisterComponent,
      },
      {
        path: 'logout',
        component: DxLogoutComponent,
      },
      {
        path: 'request-password',
        component: DxRequestPasswordComponent,
      },
      {
        path: 'reset-password',
        component: DxResetPasswordComponent, 
      },
    ],
  },
  { path: '', redirectTo: 'pages', pathMatch: 'full' },
  { path: '**', redirectTo: 'pages' },
];
```

**Comment by Safo91** [comment] 2018-05-28 20:15
I did, here is my project: [ngx-admin.zip](https://github.com/akveo/nebular/files/2035491/ngx-admin.zip)

is my routing.module.ts fine? I made sure to point to the one I copied over.

**Comment by nnixaa** [comment] 2018-10-09 08:37
Since we released the updated documentation (https://akveo.github.io/nebular/docs/auth/custom-auth-components) I guess we are good to close this one.

**Closed by nnixaa** 2018-10-09 08:37 UTC
Labels: module:auth, needs info, question
