### ISSUE TITLE
Nebular menu item distorted

### ISSUE THREAD

**Issue by anishThomas4419** [akveo/nebular#96] opened 2017-12-02 06:29 UTC
Hi,
I am trying to add a drag and drop feature for the menu items in akveo/ngx-admin project. For this I have used the menu folder from nebular framework instead of nb-menu from node modules. However the menu items are getting distorted and is failing to take the CSS of parent cosmic,/default theme. Please help me to resolve this issue. Thanks.

**Comment by nnixaa** [comment] 2017-12-19 10:47
Hi @anishThomas4419, please provide a complete reproducible example so that we can assist.

**Comment by nnixaa** [comment] 2018-01-05 09:25
Closing due to no updates.

**Closed by nnixaa** 2018-01-05 09:25 UTC
Labels: needs info
