### ISSUE TITLE
Angular 6 library compile error: Directive NbContextMenuDirective, Expected 0 arguments, but got 1.

### ISSUE THREAD

**Issue by BertrandGouny** [akveo/nebular#635] opened 2018-08-14 14:07 UTC
### Issue type

**I'm submitting a ...** 

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

Can't compile angular 6 library using `NbContextMenuDirective` got the error : 
`
projects/demo/src/lib/demo.component.ts.DemoComponent.html(4,7): : Directive NbContextMenuDirective, Expected 0 arguments, but got 1.
`

**Expected behavior:**

Should compile :D 

**Steps to reproduce:**
```
git clone https://github.com/osixia/nebular-bug
cd nebular-bug
npm install
ng build demo
```

**Related code:**

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'lib-demo',
  template: `
    <p>
      demo works!
      <button [nbContextMenu]="items">Click me</button>
    </p>
  `,
  styles: []
})
export class DemoComponent implements OnInit {

  items = [{ title: 'Profile' }, { title: 'Log out' }];

  constructor() { }

  ngOnInit() {
  }

}

```

### Other information:

**npm, node, OS, Browser**
```
node --version
v8.10.0

npm --version
6.2.0
```

**Angular, Nebular**
```
"@angular/core": "^6.0.3",
[...]
"@nebular/theme": "^2.0.0-rc.10",

"ng-packagr": "^3.0.0-rc.2" and "ng-packagr": "^4.1.0", tested with same result
```

**Comment by nnixaa** [comment] 2018-09-16 18:57
Hey @BertrandGouny, @arabbani, thanks for submitting this. Could you please post a reproducible example to stackblitz?

**Comment by arabbani** [comment] 2018-09-17 05:54
The error only visible while building the project for production

**Comment by BertrandGouny** [comment] 2018-09-17 06:41
Hello,
i made a github repo to reproduce the issue : 
```
git clone https://github.com/osixia/nebular-bug
cd nebular-bug
npm install
ng build demo
```

**Comment by nnixaa** [comment] 2018-09-17 09:35
@BertrandGouny thanks! Here is the reason https://github.com/akveo/nebular/blob/2.0.0-rc.10/src/framework/theme/components/context-menu/context-menu.directive.ts#L168 and here is the explanation https://stackoverflow.com/a/50409526/6272699.

Since we rework the popover based components quite a lot since the previous RC, we need to check if this is still the case.

On a side note, the demo component is missing `<nb-layout><nb-layout-column>...</` which are required by Nebular.

**Comment by nnixaa** [comment] 2018-09-17 10:11
Just tried with the build master package and it works fine:
![image](https://user-images.githubusercontent.com/230527/45617482-2b992280-ba7b-11e8-9355-9c30b20bc5fd.png)
Will be published in the next 2.0.0 version, closing.

**Closed by nnixaa** 2018-09-17 10:11 UTC
Labels: module:theme

**Comment by arabbani** [comment] 2018-09-18 04:54
Thankx. When version 2 will come out

**Comment by nnixaa** [comment] 2018-09-30 16:05
@arabbani next week!
