### ISSUE TITLE
NbStep ignoring [completed] when the next step is clicked

### ISSUE THREAD

**Issue by ilDon** [akveo/nebular#725] opened 2018-09-18 16:38 UTC
### Issue type

**I'm submitting a ...** 

* [X] bug report
* [ ] feature request

### Issue description

When passing the parameter `completed` to NbStep (`<nb-step [completed]="false"></nb-step>`, the step is marked as completed when another step is selected by clicking on the step number, even if the value of `competed` is `false`.

**Expected behavior:**

When passing the value of `completed` the step should be set as completed only if the value is `true`.

**Steps to reproduce:**

- Create a stepper with at lease to steps;
- Set `completed` to `false` for the first step.
- Click on the second step.
- Notice that the first step is marked as completed.

**Comment by lexzhukov** [comment] 2018-10-15 11:46
Hello @ilDon. 
I can't reproduce this issue. Could you create a working example on stackblitz? 
Thanks!

**Comment by nnixaa** [comment] 2019-02-20 09:57
Closing as it's been a while.

**Closed by nnixaa** 2019-02-20 09:57 UTC
Labels: Backlog, P2: important, bug, module:theme, needs info

**Comment by LuisUrrutia** [comment] 2020-02-28 20:06
Same problem

**Comment by gemins** [comment] 2020-04-03 22:32
Hello i have the same problem,  an example:
<nb-step label="Stock" [completed]="stockValid"></nb-step>

let stockValid = false;

never change this variable, but if i change to the next or another step, this step "Stock" is checked like a complete the same way.

Please can fix that? 

Thanksyou

**Comment by marcusvideira** [comment] 2020-05-08 22:26
Same problem here while fixing <nb-step [completed]='false'>

**Comment by gemins** [comment] 2020-05-08 22:33
i made this fix:
<nb-step label="Titulo" 
[completed]="indirectTasksHasCompleted()" 
[stepControl]="{valid: indirectTasksHasCompleted(), reset: null}">

Create a inline object with key valid and reset.

**Comment by Firekepr** [comment] 2025-03-12 11:54
For those who are still suffering from this (like I did), I solved it by doing this:

HTML
`
<nb-stepper #stepper orientation="horizontal" [selectedIndex]="currentStepIdx" [disableStepNavigation]="true">
  <nb-step label="test 1"></nb-step>
  <nb-step label="test 2"></nb-step>
  <nb-step label="test 3"></nb-step>
</nb-stepper>



    <button (click)="previousStepping()">
      <div> Back </div>
    </button>

    <button (click)="nextStepping()">
      <div> Next </div>
    </button>
`

TS
`
@ViewChild('stepper') stepperComponent: NbStepperComponent;

  public previousStepping(): void {
    this.currentStepIdx = this.currentStepIdx - 1;

    this.stepperComponent.steps.forEach((step: NbStepComponent, index: number) => {
      step.stepControl = { valid: this.currentStepIdx > index, reset: null };
    });
  }

  public nextStepping(): void {
    this.currentStepIdx = this.currentStepIdx + 1;

    this.stepperComponent.steps.forEach((step: NbStepComponent, index: number) => {
      step.stepControl = { valid: this.currentStepIdx > index, reset: null };
    });
  }
`
