### ISSUE TITLE
am not able to pass the data from till now nb dialog component

### ISSUE THREAD

**Issue by sivaadhithya** [akveo/nebular#1287] opened 2019-03-08 06:50 UTC
am not able to pass the data till now
this.dialogService.open(messagecomponent, { hasBackdrop: true, closeOnBackdropClick: true,hasScroll:false,context: { testVar: "sssss" });
_Originally posted by @sivaadhithya in https://github.com/akveo/nebular/issues/924#issuecomment-470825199_
Error
 error TS2345: Argument of type '{ hasBackdrop: true; closeOnBackdropClick: true; hasScroll: false; context: { testVar: string; }; }' is not assignable to parameter of type 'Partial<NbDialogConfig<messageComponent>>'.

**Comment by nnixaa** [comment] 2019-03-12 11:18
Closing as duplicate of https://github.com/akveo/nebular/issues/1261

**Closed by nnixaa** 2019-03-12 11:18 UTC
Labels: duplicate
