### ISSUE TITLE
Context menu does not render after router navigation

### ISSUE THREAD

**Issue by fernando-almeida** [akveo/nebular#1136] opened 2019-01-08 15:57 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Following an OAuth2 flow similar to the samples, the user context menu in the header component does not drop-down upon click and yields the following stack trace.

main.a72571efe1e9cccd811a.js:69949 ERROR TypeError: Cannot read property 'appendChild' of null
    at NbOverlayContainerAdapter.push../node_modules/@nebular/theme/components/cdk/adapter/overlay-container-adapter.js.NbOverlayContainerAdapter._createContainer (main.a72571efe1e9cccd811a.js:105528)
    at NbOverlayContainerAdapter.push../node_modules/@angular/cdk/esm5/overlay.es5.js.OverlayContainer.getContainerElement (main.a72571efe1e9cccd811a.js:11222)
    at NbOverlay.push../node_modules/@nebular/theme/components/cdk/overlay/mapping.js.NbOverlay.createHostElement (main.a72571efe1e9cccd811a.js:106080)
    at NbOverlay.push../node_modules/@nebular/theme/components/cdk/overlay/mapping.js.NbOverlay.create (main.a72571efe1e9cccd811a.js:106055)
    at NbOverlayService.push../node_modules/@nebular/theme/components/cdk/overlay/overlay.js.NbOverlayService.create (main.a72571efe1e9cccd811a.js:106832)
    at NbContextMenuDirective.push../node_modules/@nebular/theme/components/context-menu/context-menu.directive.js.NbContextMenuDirective.createOverlay (main.a72571efe1e9cccd811a.js:108818)
    at NbContextMenuDirective.push../node_modules/@nebular/theme/components/context-menu/context-menu.directive.js.NbContextMenuDirective.show (main.a72571efe1e9cccd811a.js:108798)
    at SafeSubscriber._next (main.a72571efe1e9cccd811a.js:108855)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (main.a72571efe1e9cccd811a.js:137557)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (main.a72571efe1e9cccd811a.js:137495)

**Expected behavior:**
The user context menu will show upon click after router navigation.

**Steps to reproduce:**
The callback code that's triggering the issue is in the akveo/nebular repo.
https://github.com/akveo/nebular/blob/7e68c20a92dbe8f86ff728f0df6d4e771a0b7408/src/playground/with-layout/oauth2/oauth2-callback.component.ts

I even tried a variation of the existing logic by running it within OnInit and OnDestroy with the appropriate subscription disposable. It yields the same results.
The only thing that makes the user context menu to start rendering again is a hard-refresh of the browser.

**Related code:**

### Other information:

**npm, node, OS, Browser**
```
Node, npm: `node --version` (v11.4.0) and `npm --version` (6.4.1)
OS: macOS Mojave
Browser: Chrome
```

**Angular, Nebular**
```
    "@nebular/auth": "3.1.0",
    "@nebular/bootstrap": "3.1.0",
    "@nebular/security": "3.1.0",
    "@nebular/theme": "3.1.0",
```

**Comment by MaSydJun** [comment] 2019-01-11 21:52
Yep, having the same issue with _NbPasswordAuthStrategy_.

**Comment by nnixaa** [comment] 2019-02-28 09:06
Cannot reproduce it. Could you someone consolidate a reproducible example at https://stackblitz.com/github/akveo/nebular-seed?

**Comment by Mubramaj** [comment] 2019-03-07 17:10
I can confirm this issue on Nebular 3.4.0

**Comment by nnixaa** [comment] 2019-04-11 08:22
@Mubramaj, could you shed a bit more light, please? What would be the steps? Are there any changes to layout/routes/etc?

**Comment by Mayocampo** [comment] 2019-04-19 20:09
Same error when trying to load nb-select inside Lazy-loaded feature module. A few days ago the same code was working with angular core at v7.2.9 and CDK at v7.3.4

Now i'm getting this same error with angular core at v7.2.13 and CDK at v7.3.7

    "@angular/animations": "^7.2.13",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.13",
    "@angular/compiler": "^7.2.13",
    "@angular/compiler-cli": "^7.2.13",
    "@angular/core": "^7.2.13",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.13",
    "@angular/http": "^7.2.13",
    "@angular/platform-browser": "^7.2.13",
    "@angular/platform-browser-dynamic": "^7.2.13",
    "@angular/router": "^7.2.13",
    "@nebular/auth": "3.1.0",
    "@nebular/bootstrap": "3.1.0",
    "@nebular/security": "3.1.0",
    "@nebular/theme": "3.1.0",
    "@ng-bootstrap/ng-bootstrap": "^4.1.0"

**Comment by Roman-Simik** [comment] 2019-04-23 12:52
Hi, this must be propably related also to my issue [#1273](https://github.com/akveo/nebular/issues/1273#issue-416553652). 
You @nnixaa marked it as fixed and closed it in new nebular version - [3.4.2](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#342-2019-03-31), **but the problem is that this bug still isn't fixed** - the context menu still won't open after parent element is "refreshed". (check this [Stackblitz](https://stackblitz.com/edit/github-fnq8mz-6sefyj) example).

**Comment by sancaruso** [comment] 2019-05-28 13:23
Same issue for me with nebular 3.5.0 : just after login I have the same error message when I try to open a dialog. No error if I was already logged when I run the application.

**Comment by LucasLopesr** [comment] 2019-06-07 13:11
same problem

**Comment by Gilmar-Gomes** [comment] 2019-06-08 20:07
same problem!

**Comment by Gilmar-Gomes** [comment] 2019-06-08 20:11
I beleave that is something related to NbOverlayContainerAdapter._containerElement member (is showing null in vscode debugger). So, when it calls getContainerElement().appendChild throws the error!

**Comment by LucasLopesr** [comment] 2019-06-09 16:35
Someone got some palliative solution?

**Comment by lepidotteri** [comment] 2019-07-01 14:43
This issue effectively impedes the usage of the otherwise excellent ContextMenu and Dialog components and it should not be postponed any further

**Comment by longgt** [comment] 2019-08-05 09:30
I have same issue when combined `nbContextMenu` directive with `nb-route-tabset`.
In https://angular-7-master-6mmzen.stackblitz.io/ (Edit URL: https://stackblitz.com/edit/angular-7-master-6mmzen)

**[Reproduce steps]**

1. App starts with AboutPage (Click `Settings` at the top-left corner will show context menu)
2. Switch to ContactPage
At this time, `nbContextMenu` in shared component will not work anymore.

**Comment by rushi721** [comment] 2019-08-08 11:12
I have the same problem.
Error is as follows :-
`ERROR TypeError: Cannot read property 'appendChild' of null
    at NbOverlayContainerAdapter._createContainer (index.js:997)
    at NbOverlayContainerAdapter.getContainerElement (overlay.js:766)
    at NbOverlay._createHostElement (overlay.js:3177)
    at NbOverlay.create (overlay.js:3136)
    at NbOverlayService.create (index.js:1464)
    at NbSelectComponent.createOverlay (index.js:18650)
    at NbSelectComponent.attachToOverlay (index.js:18632)
    at NbSelectComponent.show (index.js:18537)
    at SafeSubscriber._next (index.js:18673)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)`

**Closed** 2019-08-21 12:14 UTC
Labels: bug, module:components, needs info, quality

**Comment by NileshDabi** [comment] 2019-10-08 06:44
I also have the same problem with nebular toastr. Its not working in my lazy loaded feature module.

**Comment by niklasravnsborg** [comment] 2019-11-04 16:02
I still got the issue in version 4.5.0

```
ERROR TypeError: Cannot read property 'appendChild' of null
    at NbOverlayContainerAdapter._createContainer (index.js:1043)
    at NbOverlayContainerAdapter.getContainerElement (overlay.js:768)
    at NbOverlay._createHostElement (overlay.js:3203)
    at NbOverlay.create (overlay.js:3162)
    at NbOverlayService.create (index.js:1647)
    at NbDynamicOverlay.createOverlay (index.js:11878)
    at NbDynamicOverlay.show (index.js:11841)
    at SafeSubscriber._next (index.js:12077)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
```

**Comment by JrmyDev** [comment] 2019-11-05 11:15
3.6.2 seems to fix this issue

**Comment by lepidotteri** [comment] 2019-11-05 11:41
> 3.6.2 seems to fix this issue
no it does not, at least when there are lazy-loaded modules in the way

> I still got the issue in version 4.5.0
> 
> ```
> ERROR TypeError: Cannot read property 'appendChild' of null
>     at NbOverlayContainerAdapter._createContainer (index.js:1043)
>     at NbOverlayContainerAdapter.getContainerElement (overlay.js:768)
>     at NbOverlay._createHostElement (overlay.js:3203)
>     at NbOverlay.create (overlay.js:3162)
>     at NbOverlayService.create (index.js:1647)
>     at NbDynamicOverlay.createOverlay (index.js:11878)
>     at NbDynamicOverlay.show (index.js:11841)
>     at SafeSubscriber._next (index.js:12077)
>     at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
>     at SafeSubscriber.next (Subscriber.js:122)
> ```

same here.. so frustrating, can't get around it with Context Menus, had to swap a different navigation menu system for production release

**Comment by niklasravnsborg** [comment] 2019-11-05 13:46
@lepidotteri I used Nebular Auth and had to write a custom AuthComponent that doesn't use `<nb-layout>` itself, by default it does:

https://github.com/akveo/nebular/blob/1e1a293d189cc63f15a53c9e69682ee754fbc149/src/framework/auth/components/auth.component.ts#L16-L33

From my understanding the menu only works correctly if the `<nb-layout>` stays consistent throughout navigation.

**Comment by lepidotteri** [comment] 2019-11-05 14:17
> @lepidotteri I used Nebular Auth and had to write a custom AuthComponent that doesn't use `<nb-layout>` itself, by default it does:
> 
> https://github.com/akveo/nebular/blob/1e1a293d189cc63f15a53c9e69682ee754fbc149/src/framework/auth/components/auth.component.ts#L16-L33
> 
> From my understanding the menu only works correctly if the `<nb-layout>` stays consistent throughout navigation.

Thank you @niklasravnsborg, I had suspected as much; I didn't go that far but I did change the auth-module routes to test the behavior and it was working fine then.

I think they should either:
 1. change the component to be more standalone and resilient
 2. make NbMenuComponent more suitable (doesn't even have orientation atm?) and customizable for top-bar navigation purposes

**Comment by MrDarkSkil** [comment] 2020-01-18 16:50
I have the same problem with 4.6.0 version of nebular.

```js
<nb-action *ngIf="isLoggedIn">
    <nb-user [name]="user?.name" [picture]="'https://www.gravatar.com/avatar/' + user?.email_hash"
      [nbContextMenu]="accountMenuActions" nbContextMenuTag="account-menu" nbContextMenuTrigger="hover">
    </nb-user>
</nb-action>
```


If i logout and login again i have the same error.

```logs
ERROR TypeError: Cannot read property 'appendChild' of null
    at NbOverlayContainerAdapter._createContainer (index.js:1043)
    at NbOverlayContainerAdapter.getContainerElement (overlay.js:768)
    at NbOverlay._createHostElement (overlay.js:3203)
    at NbOverlay.create (overlay.js:3162)
    at NbOverlayService.create (index.js:1637)
    at NbDynamicOverlay.createOverlay (index.js:11473)
    at NbDynamicOverlay.show (index.js:11436)
    at SafeSubscriber._next (index.js:11672)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
```

It can aslo appear after navigation on specific routes, always the same routes.

**Comment by mc-lovin** [comment] 2020-04-11 14:39
What @niklasravnsborg suggested worked for me. The `nb-layout` tag needs to be consistent in the outer layout. i.e. it should always be the same outer `nb-layout` tag which is containing other layouts

**Comment by dcruz1990** [comment] 2020-04-21 19:24
Whats the fix for this? im having same issue.

**Comment by MrDarkSkil** [comment] 2020-04-21 19:30
I don't remember exactly but do you use multiple <nb-layout> in your projects ? 
Personally i used many <nb-layout> in multiple vues, when i found a alternative to this it fixed so i think is linked :)

**Comment by tekmi** [comment] 2020-07-17 12:44
I have experienced the same error: `ERROR TypeError: Cannot read property 'appendChild' of null` while I was playing with the `nb-user` component:

```html
<nb-action class="user-action" *ngIf="isAuth">
      <nb-user
        [nbContextMenu]="userMenu"
        nbContextMenuTag="user-context-menu"
        [name]="user?.email"
        [onlyPicture]="userPictureOnly"
        [picture]="user?.picture">
      </nb-user>
</nb-action>
```

I could not load the `userMenu` context menu, only the hard refresh was bringing the things to normal...but this was not the ideal solution.

My main app component used the `<app-header>` component which had the offending `<nb-user>` component, as shown below :

```html
<nb-layout>
  <nb-layout-header fixed>
    <app-header></app-header>
  </nb-layout-header>

  <nb-layout-column>
    <router-outlet></router-outlet>
  </nb-layout-column>

  <nb-layout-footer fixed>
    Footer
  </nb-layout-footer>
</nb-layout>
```

During route changes, my `<router-outlet></router-outlet>` was being replaced by the auth component which is presented below:

```html
<nb-layout>
  <nb-layout-column>
    <nb-card>
      <nb-card-header>
        <nav class="navigation">Authentication</nav>
      </nb-card-header>
      <nb-card-body>
        <app-auth-block>
          <router-outlet></router-outlet>
        </app-auth-block>
      </nb-card-body>
    </nb-card>
  </nb-layout-column>
</nb-layout>
```

The surprising fix was to remove the `<nb-layout>` and `<nb-layout-column>` parts from my auth component...thus here it is how it looks now:

```
<nb-card>
  <nb-card-header>
    <nav class="navigation">Authentication</nav>
  </nb-card-header>
  <nb-card-body>
    <app-auth-block>
      <router-outlet></router-outlet>
    </app-auth-block>
  </nb-card-body>
</nb-card>
```

Thanks to this trick the error is gone and I can see the context menu while clicking on the user icon. 

I hope this confirms that the error still exists, even in `@nebular/theme: "^5.1.0"` version. Plus, the suggestions from previous people here, that having only one `<nb-layout>` surprisingly fixes this weird error. Thank you guys!

**Comment by vonbeitthia** [comment] 2021-04-30 23:27
solved adding one space in path definition:
const rutas: Routes = [
    { path: 'clientes', 
    loadChildren: () => import('./clientes/clientes.module').then(m => m.ClientesModule) 
    },
    { 
    path: ' ', // para no generar errores debe estar en blanco
    component: AppComponent,
    pathMatch: 'full'
    }
];

**Comment by truonghoangduy** [comment] 2021-05-13 07:40
I resolve the issue here #1663 [link](https://github.com/akveo/nebular/issues/1663#issuecomment-675133115)
