### ISSUE TITLE
Datepicker two-way data binding bug ( version 3.0.0 ) 

### ISSUE THREAD

**Issue by Yang-tzu-yi** [akveo/nebular#1102] opened 2018-12-21 04:45 UTC
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'format' of null
TypeError: Cannot read property 'format' of null
    at NbMomentDateService.push../node_modules/@nebular/moment/services/moment-date.service.js.NbMomentDateService.format (moment-date.service.js:70)
    at NbDateAdapterService.push../node_modules/@nebular/theme/components/datepicker/datepicker-adapter.js.NbDateAdapterService.format (datepicker-adapter.js:44)
    at NbDatepickerDirective.push../node_modules/@nebular/theme/components/datepicker/datepicker.directive.js.NbDatepickerDirective.writeInput (datepicker.directive.js:289)
    at NbDatepickerDirective.push../node_modules/@nebular/theme/components/datepicker/datepicker.directive.js.NbDatepickerDirective.writeValue (datepicker.directive.js:192)
    at setUpControl (forms.js:2007)
    at forms.js:4224
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:16156)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at resolvePromise (zone.js:814)
    at zone.js:877
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:16147)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
```

**Expected behavior:**

Expected two-way data binding to be working with datepicker component

**Steps to reproduce:**

```html
<input nbInput [nbDatepicker]="enddatepicker" [(ngModel)]="enddate" name="enddate">
<nb-datepicker format="YYYY/MM/DD" #enddatepicker></nb-datepicker>
```

```js
this.enddate = moment();
```

### Other information:

**npm, node, OS, Browser**
```
<!--
OS: macOS
npm: 6.4.1
node: 10.12.0
-->
```

**Angular, Nebular**
```
Angular 7.1.4
Nebular 3.0.0
```

**Comment by XTalandier** [comment] 2019-01-12 08:15
Same issue here

**Comment by sameerpallav** [comment] 2019-02-15 14:43
You need to install and include NbMomentDateModule from '@nebular/moment' for it to work.

**Comment by Tibing** [comment] 2019-02-15 16:06
@Yang-tzu-yi, hi there, comment above looks like the solution, so, I'm closing the issue.
If the issue isn't resolved, please, reopen it.

**Closed by Tibing** 2019-02-15 16:06 UTC
Labels: Backlog, P2: important, Sprint, bug, module:components

**Comment by leduclinh7141** [comment] 2019-03-12 09:51
I have same issue. I added NbMomentDateModule but nothing change. 2 way binding is not work. Anyone has any solution for this?

**Comment by nnixaa** [comment] 2019-03-12 12:40
@leduclinh7141 could you open a new issue with a reproducible example, please? You can use https://stackblitz.com/github/akveo/nebular-seed as a starter.
